server:
  port: 9997
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 10240000


spring:
  freemarker:
    checkTemplateLocation: false
  thymeleaf:
    mode: HTML
    cache: false
    suffix: .html
    encoding: UTF-8


  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true

  datasource:
    driver-class-name: org.h2.Driver
    # schema: classpath:db/schema.sql
    # data: classpath:db/data.sql
#    url: jdbc:h2:file:F:\filesystem\db\h2db
    url: jdbc:h2:file:.\db\h2db
    username: root
    password: 123456
    platform: h2
    type: com.zaxxer.hikari.HikariDataSource

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

file-share:
  # file-path: /Users/zhaojianmin/IdeaProjects/file-share/file