server:
  port: 9997
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 10240000


spring:
  freemarker:
    checkTemplateLocation: false
  thymeleaf:
    mode: HTML
    cache: false
    suffix: .html
    encoding: UTF-8


  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true

  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://47.98.179.50:5432/file_share
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      register-mbeans: true
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: select 1

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

# 配置sql打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.space.freereport.mapper: debug

file-share:
  # file-path: /Users/zhaojianmin/IdeaProjects/file-share/file
