server:
  port: 9996
  tomcat:
    uri-encoding: UTF-8

spring:
  freemarker:
    checkTemplateLocation: false
  thymeleaf:
    mode: HTML
    cache: false
    suffix: .html
    encoding: UTF-8

  # ???? 404 ??
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.h2.Driver
    #schema: classpath:db/schema.sql #??????????????schema.sql????????????
    #data: classpath:db/data.sql #??????????????data.sql????????????
    url: jdbc:h2:file:./db/h2db #??h2??????????????????
    username: root
    password: 123456

  h2:
    console:
      enabled: true #??web console??

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

file-share:
  # file-path: /Users/zhaojianmin/IdeaProjects/file-share/file